# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
"""Build tests/fixtures/z2m_actions.json: every Z2M device's action list.

Reads the device definitions in a zigbee-herdsman-converters checkout
(the library Zigbee2MQTT gets its device support from) and records, per
model, the literal ``action`` enum and the buttons ``group_buttons`` makes
of it. tests/test_z2m_catalog.py asserts the grouping still matches, so a
parser change shows up as a diff of this file.

Only literal lists are picked up: ``e.action([...])`` and ``actionLookup``
keys. Actions generated by helpers (``m.commandsOnOff``, IKEA extends) are
not.

Refresh from upstream:
    git clone --depth 1 --filter=blob:none --sparse \\
        https://github.com/Koenkk/zigbee-herdsman-converters.git <dir>
    git -C <dir> sparse-checkout set src/devices
    python3 scripts/z2m_actions.py <dir>

After an intended parser change, re-group the saved lists without a checkout:
    python3 scripts/z2m_actions.py --regroup
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from itertools import pairwise
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from custom_components.remote_mapper.buttons import group_buttons  # noqa: E402

FIXTURE = ROOT / "tests/fixtures/z2m_actions.json"

MODEL = re.compile(r'\bmodel:\s*"([^"]+)"')
VENDOR = re.compile(r'\bvendor:\s*"([^"]+)"')
DESCRIPTION = re.compile(r'\bdescription:\s*"([^"]+)"')
DEVICE_START = re.compile(r"\{\s*\n\s*(?:zigbeeModel|fingerprint):")
ACTION_LIST = re.compile(r"e\.action\(\s*\[(.*?)\]\s*\)", re.S)
ACTION_LOOKUP = re.compile(r"actionLookup:\s*\{(.*?)\}", re.S)
STRING = re.compile(r'"([^"\\]*)"')
KEY = re.compile(r'(?:^|[,{\s])"?([A-Za-z0-9_]+)"?\s*:', re.M)


def grouped(actions: list[str]) -> dict[str, list[str]]:
    """Button id → its events, as the card gets them."""
    return {
        button["id"]: [action["event"] for action in button["actions"]]
        for button in group_buttons("device_trigger", actions)
    }


def extract(checkout: Path) -> list[dict]:
    """One entry per device definition with a literal action list."""
    devices = []
    for path in sorted((checkout / "src/devices").glob("*.ts")):
        text = path.read_text()
        starts = [m.start() for m in DEVICE_START.finditer(text)] + [len(text)]
        for start, end in pairwise(starts):
            block = text[start:end]
            if not (model := MODEL.search(block)):
                continue
            actions: list[str] = []
            for m in ACTION_LIST.finditer(block):
                actions += STRING.findall(m.group(1))
            for m in ACTION_LOOKUP.finditer(block):
                actions += KEY.findall(m.group(1))
            actions = list(dict.fromkeys(a for a in actions if a))
            if not actions:
                continue
            vendor = VENDOR.search(block)
            description = DESCRIPTION.search(block)
            devices.append(
                {
                    "model": model.group(1),
                    "vendor": vendor.group(1) if vendor else "",
                    "description": description.group(1) if description else "",
                    "actions": actions,
                }
            )
    return devices


def write(source: dict, devices: list[dict]) -> None:
    """One device per line, so a grouping change is a one-line diff."""
    for device in devices:
        device["buttons"] = grouped(device["actions"])
    lines = ",\n".join(json.dumps(d, ensure_ascii=False) for d in devices)
    header = json.dumps(source, ensure_ascii=False)
    FIXTURE.parent.mkdir(exist_ok=True)
    FIXTURE.write_text(f'{{"source": {header},\n"devices": [\n{lines}\n]}}\n')
    print(f"{len(devices)} devices → {FIXTURE.relative_to(ROOT)}")


def main() -> None:
    if sys.argv[1:] == ["--regroup"]:
        saved = json.loads(FIXTURE.read_text())
        write(saved["source"], saved["devices"])
        return
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    checkout = Path(sys.argv[1])
    commit = subprocess.run(
        ["git", "-C", str(checkout), "log", "-1", "--format=%H %cs"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.split()
    source = {
        "repo": "https://github.com/Koenkk/zigbee-herdsman-converters",
        "commit": commit[0],
        "date": commit[1],
        "regenerate": "python3 scripts/z2m_actions.py <checkout>; steps in its "
        "docstring. After a parser change: --regroup",
    }
    write(source, extract(checkout))


if __name__ == "__main__":
    main()
